export const ADD_ACCOUNT_LINK = 'ADD_ACCOUNT_LINK';
export const GET_LOCATIONS = 'GET_LOCATIONS';
export const GET_CURRENT_LOCATION = 'GET_CURRENT_LOCATION';
export const ADD_TO_LOCATIONS = 'ADD_TO_LOCATIONS';
